name: SailfishOS build

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - master

env:
  RELEASE: 4.6.0.13
  SYNCTHING_VERSION: 2.0.16

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - arch: armv7hl
            syncthing_arch: arm
          - arch: aarch64
            syncthing_arch: arm64
          - arch: i486
            syncthing_arch: 386
    
    steps:
    - uses: actions/checkout@v5

    - name: prepare
      run: mkdir RPMS

    - name: Build ${{ matrix.arch }}
      run: docker run --rm --privileged -v $PWD:/workspace coderus/sailfishos-platform-sdk:$RELEASE /bin/bash -c "
            mkdir -p build ;
            cd build ;
            cp -r /workspace/* . ;
            cd rpm ;
            curl -OL https://github.com/syncthing/syncthing/releases/download/v${SYNCTHING_VERSION}/syncthing-linux-${{ matrix.syncthing_arch }}-v${SYNCTHING_VERSION}.tar.gz ;
            cd .. ;
            mb2 -t SailfishOS-$RELEASE-${{ matrix.arch }} build --prepare ;
            sudo cp -r RPMS/*.rpm /workspace/RPMS"

    - name: Upload build result
      uses: actions/upload-artifact@v5
      with:
        name: rpms-${{ matrix.arch }}
        path: RPMS
